### ISSUE TITLE
是不是开发vpn的类型都是Chines？

### ISSUE THREAD

**Issue by fanmingyi** [heiher/hev-htproxy#1]
= = 我在好奇你是不是 我大天朝的__

**Comment by heiher** [comment]
有且不仅有

**Comment by fanmingyi** [comment]
对了你这个用了没效果呢，无法连接s5服务器。正好想实现透明代理s5 。proxyDroid可以实现

**Comment by heiher** [comment]
是的，因为集成的预编译socks5 client并不是标准的socks5协议。

**Comment by fanmingyi** [comment]
兄弟你这个有可以链接的完整代码吗？proxydroid代码看着太多了，我看你这比较简单

**Comment by heiher** [comment]
匹配这个客户端的socks5 server也是不开源的，但可以给你一个预编译的Linux或macOS版本。
