### ISSUE TITLE
直接clone下来用不了！！！

### ISSUE THREAD

**Issue by xiandon** [heiher/hev-htproxy#2]
couldn't find "libhev-socks5-tunnel.so"  --找不到这个so文件，保存的setConfigs是什么格式呀？IP+端口号吗？无加密的socks5能用吗？

**Comment by heiher** [comment]
私有软件，不建议使用哈。:)

**Comment by xiandon** [comment]
我主要也是用于学习，可以给个可以运行的完整源码吗？

**Comment by heiher** [comment]
作为参考实现是OK的，我大概介绍一下这个项目的结构和模块间的关系：

这个项目是通过创建一个Global或perApp的Android VPN Service提供系统全局或部分应用的网络访问服务的。其中Java主要是UI、配置和VPN Service的实现、对接。关键实现部分在JNI，共有两个组件：
#### hev-socks5-tunnel
[HS5T](https://github.com/heiher/hev-socks5-tunnel)是个开源项目，负载对接VPN Service的IP流量，解复用TCP流量，并将TCP、DNS流量通过Socks5代理。其中DNS的支持是在Socks5上扩展的私有命令实现，[HS5S](https://github.com/heiher/hev-socks5-server)项目实现了该命令。

#### hev-socks5-client
HS5C是一个Socks5 service provider，它是私有项目，也是该项目中唯一缺失源代码的部分。负载将远端的HS5S的Socks5代理业务映射到本地来对HS5T提供Socks5服务，默认配置侦听在TCP 127.0.0.1:1080。
```
    127.0.0.1:1080 <--混淆/加密--> [remote addr]:1080 (HS5S)
```
