### ISSUE TITLE
hev-htproxy\app\src\main\jni\hev-socks5-tunnel\third-part\yaml\include\yaml.h:1:1: error: expected identifier or '('

### ISSUE THREAD

**Issue by btcw** [heiher/hev-htproxy#5]

**Comment by heiher** [comment]
看上去是因为编译环境的文件系统不支持符号链接，所以yaml.h被作为普通文件处理，内容就不对了。

另外，这个项目实际上并开源的私有项目，只具备Android VPN实现与Tunnel to Socks5使用的参考意义，因为其中Socks5Client JNI库是不开源的，不过这个库除了传输混淆以外对内等价于在127.0.0.1:1080提供Socks5服务([HS5S兼容](https://github.com/heiher/hev-socks5-server))，对接后能用。

**Comment by btcw** [comment]
哦哦，我现在在做一个socks5的项目，所以想找一个能在android上运行并支持账号/密码验证的开源项目看看，请问大佬有推荐么

**Comment by heiher** [comment]
那应该是指Socks5服务端吧，[HS5S](https://github.com/heiher/hev-socks5-server)是可以的，暂时只能编译为独立可执行文件，因为之前没有集成JNI库的需求，不过很容易加上。

**Comment by btcw** [comment]
好的，谢谢
