### ISSUE TITLE
In file included from E:\socks5-htproxy\hev-htproxy\app\src\main\jni\hev-socks5-tunnel\src\hev-socks5-session.c:14: E:\socks5-htproxy\hev-htproxy\app\src\main\jni\hev-socks5-tunnel\third-part\hev-task-system\include\hev-task.h:1:1: error: expected identifier or '('

### ISSUE THREAD

**Issue by siromidz** [heiher/hev-htproxy#6]
hi
when building, i face this error:

In file included from E:\socks5-htproxy\hev-htproxy\app\src\main\jni\hev-socks5-tunnel\src\hev-socks5-session.c:14:
E:\socks5-htproxy\hev-htproxy\app\src\main\jni\hev-socks5-tunnel\third-part\hev-task-system\include\hev-task.h:1:1: error: expected identifier or '('

**Comment by heiher** [comment]
This error is because the Windows file system does not support symbolic links.

This project is partially open source and contains a library for private protocol, I think it cannot be used for you directly. For reference only.
