### ISSUE TITLE
能提供这so的源码吗

### ISSUE THREAD

**Issue by moz1q1** [heiher/hev-htproxy#8]
hev-http-stream.so

**Comment by heiher** [comment]
这一部分是不开源的，但可以提供这一部分与其它模块协作的接口，可以根据自我需求实现来替换，哈哈。

http-stream以jni的形式运行，在配置指定的地址端口(127.0.0.1:1080)上开设socks5服务，socks5需要支持udp over tcp的扩展，比如转发 hev-socks5-server 的服务端口。

socks5-server: https://github.com/heiher/hev-socks5-server

**Comment by moz1q1** [comment]
新发的GitHub是android本地开启socks5服务？？跟http-stream有什么不一样，http-stream里面做了什么操作呢
    private static native void HStreamStartService(String config_path);

    private static native void HStreamStopService();

**Comment by heiher** [comment]
http-stream是通过端口转发把远程的socks5服务映射到本地的127.0.0.1:1080，提供给socks5-tunnel访问。http-stream还有传输层加密的功能，没有对应的服务端配套，是无法直接使用的。

**Comment by moz1q1** [comment]
那对应配套服务器代码是什么呢
