### ISSUE TITLE
hey,bro! I have my own socks server, how can i link app to it?

### ISSUE THREAD

**Issue by ukhack** [heiher/hev-htproxy#9]
嘿！大兄弟。
我看到这个app好像需要起一个专用的后端，但是我自己有一个基于v2ray的服务，附带了一个socks5服务 可以通过socks5://xxx.xx.x.x:3000的形式直接连接上去。
请问让这个app直接连接到我自己的服务最简单的方式是什么呢

**Comment by heiher** [comment]
不支持的

**Comment by ukhack** [comment]
> 不支持的

需要进行改造？

**Comment by heiher** [comment]
> > 不支持的
> 
> 需要进行改造？

是的。目前有两方面限制：
1. 依赖闭源的传输层模块才能工作。
2. 实现tun2socks的hev-socks5-tunnel需要适配hev-socks5-server才能支持UDP。
